// Source: https://leetcode.com/problems/lexicographically-smallest-generated-string/
// Author: Tom Murphy https://github.com/murphy-codes/
// Date: 2026-03-29
// At the time of submission:
//   Runtime 3 ms Beats 100.00%
//   Memory 46.62 MB Beats 70.83%

/****************************************
* 
* You are given two strings, `str1` and `str2`, of lengths `n` and `m`, respectively.
* A string `word` of length `n + m - 1` is defined to be generated by `str1` and
* _ `str2` if it satisfies the following conditions for each index `0 <= i <= n - 1`:
* • If `str1[i] == 'T'`, the substring of `word` with size `m` starting at index
* __ `i` is equal to `str2`, i.e., `word[i..(i + m - 1)] == str2`.
* • If `str1[i] == 'F'`, the substring of `word` with size `m` starting at index
* __ `i` is not equal to `str2`, i.e., `word[i..(i + m - 1)] != str2`.
* Return the lexicographically smallest possible string that can be generated by
* _ `str1` and `str2`. If no string can be generated, return an empty string `""`.
*
* Example 1:
* Input: str1 = "TFTF", str2 = "ab"
* Output: "ababa"
* Explanation:
* The table below represents the string `"ababa"`
* Index	T/F	Substring of length `m`
* 0	`'T'`	"ab"
* 1	`'F'`	"ba"
* 2	`'T'`	"ab"
* 3	`'F'`	"ba"
* The strings `"ababa"` and `"ababb"` can be generated by `str1` and `str2`.
* Return `"ababa`" since it is the lexicographically smaller string.
*
* Example 2:
* Input: str1 = "TFTF", str2 = "abc"
* Output: ""
* Explanation:
* No string that satisfies the conditions can be generated.
*
* Example 3:
* Input: str1 = "F", str2 = "d"
* Output: "a"
*
* Constraints:
* • `1 <= n == str1.length <= 10^4`
* • `1 <= m == str2.length <= 500`
* • `str1` consists only of `'T'` or `'F'`.
* • `str2` consists only of lowercase English characters.
* 
****************************************/

import java.util.Arrays;

class Solution {
    // Use Z-function to efficiently validate overlaps and substring matches.
    // First enforce 'T' constraints by ensuring overlapping placements of
    // pattern are consistent using Z-array prefix checks. Fill remaining
    // positions with 'a' to minimize lexicographic order.
    // For 'F', detect full matches using Z and break them at nearest
    // modifiable position. Time: O(n + m); Space: O(n + m).
    public String generateString(String str1, String pattern) {
        char[] flags = str1.toCharArray();
        int n = flags.length;
        int m = pattern.length();

        char[] result = new char[n + m - 1];
        Arrays.fill(result, '?');

        // Precompute Z-array for pattern
        int[] zPattern = calcZ(pattern);

        int lastTIndex = -m;

        // Step 1: Process 'T' constraints
        for (int i = 0; i < n; i++) {
            if (flags[i] != 'T') continue;

            int overlap = Math.max(lastTIndex + m - i, 0);

            // Validate overlap consistency
            if (overlap > 0 && zPattern[m - overlap] < overlap) {
                return "";
            }

            // Fill non-overlapping portion
            for (int j = overlap; j < m; j++) {
                result[i + j] = pattern.charAt(j);
            }

            lastTIndex = i;
        }

        // Track nearest '?' positions
        int[] lastFree = new int[result.length];
        int last = -1;

        for (int i = 0; i < result.length; i++) {
            if (result[i] == '?') {
                result[i] = 'a'; // minimal lexicographic
                last = i;
            }
            lastFree[i] = last;
        }

        // Compute Z-array for pattern + result
        int[] zCombined = calcZ(pattern + new String(result));

        // Step 2: Process 'F' constraints
        for (int i = 0; i < n; i++) {
            if (flags[i] != 'F') continue;

            // If already not matching, skip
            if (zCombined[m + i] < m) continue;

            // Find rightmost modifiable position
            int j = lastFree[i + m - 1];

            if (j < i) return "";

            result[j] = 'b'; // minimally break match
            i = j; // jump forward
        }

        return new String(result);
    }

    private int[] calcZ(String str) {
        char[] s = str.toCharArray();
        int n = s.length;
        int[] z = new int[n];

        int left = 0, right = 0;

        for (int i = 1; i < n; i++) {
            if (i <= right) {
                z[i] = Math.min(z[i - left], right - i + 1);
            }

            while (i + z[i] < n && s[z[i]] == s[i + z[i]]) {
                left = i;
                right = i + z[i];
                z[i]++;
            }
        }

        z[0] = n;
        return z;
    }
}