// Source: https://leetcode.com/problems/lexicographically-smallest-generated-string/
// Author: Tom Murphy https://github.com/murphy-codes/
// Date: 2026-03-29
// At the time of submission:
//   Runtime 1535 ms Beats 6.25%
//   Memory 46.60 MB Beats 70.83%

/****************************************
* 
* You are given two strings, `str1` and `str2`, of lengths `n` and `m`, respectively.
* A string `word` of length `n + m - 1` is defined to be generated by `str1` and
* _ `str2` if it satisfies the following conditions for each index `0 <= i <= n - 1`:
* • If `str1[i] == 'T'`, the substring of `word` with size `m` starting at index
* __ `i` is equal to `str2`, i.e., `word[i..(i + m - 1)] == str2`.
* • If `str1[i] == 'F'`, the substring of `word` with size `m` starting at index
* __ `i` is not equal to `str2`, i.e., `word[i..(i + m - 1)] != str2`.
* Return the lexicographically smallest possible string that can be generated by
* _ `str1` and `str2`. If no string can be generated, return an empty string `""`.
*
* Example 1:
* Input: str1 = "TFTF", str2 = "ab"
* Output: "ababa"
* Explanation:
* The table below represents the string `"ababa"`
* Index	T/F	Substring of length `m`
* 0	`'T'`	"ab"
* 1	`'F'`	"ba"
* 2	`'T'`	"ab"
* 3	`'F'`	"ba"
* The strings `"ababa"` and `"ababb"` can be generated by `str1` and `str2`.
* Return `"ababa`" since it is the lexicographically smaller string.
*
* Example 2:
* Input: str1 = "TFTF", str2 = "abc"
* Output: ""
* Explanation:
* No string that satisfies the conditions can be generated.
*
* Example 3:
* Input: str1 = "F", str2 = "d"
* Output: "a"
*
* Constraints:
* • `1 <= n == str1.length <= 10^4`
* • `1 <= m == str2.length <= 500`
* • `str1` consists only of `'T'` or `'F'`.
* • `str2` consists only of lowercase English characters.
* 
****************************************/

class Solution {
    // First enforce all 'T' constraints by placing str2 at required indices.
    // Fill remaining positions with 'a' for lexicographically smallest result.
    // For each 'F', if substring matches str2, try modifying characters to break
    // the match while ensuring no 'T' constraint is violated.
    // Time: O(n * m * 26); Space: O(n + m).
    public String generateString(String str1, String str2) {
        int n = str1.length();
        int m = str2.length();
        int L = n + m - 1;

        char[] word = new char[L];

        // Step 1: Apply 'T' constraints
        for (int i = 0; i < n; i++) {
            if (str1.charAt(i) == 'T') {
                for (int j = 0; j < m; j++) {
                    int idx = i + j;
                    if (word[idx] == 0 || word[idx] == str2.charAt(j)) {
                        word[idx] = str2.charAt(j);
                    } else {
                        return "";
                    }
                }
            }
        }

        // Step 2: Fill remaining with 'a'
        for (int i = 0; i < L; i++) {
            if (word[i] == 0) {
                word[i] = 'a';
            }
        }

        // Step 3: Fix 'F' constraints
        for (int i = 0; i < n; i++) {
            if (str1.charAt(i) == 'F') {

                if (matches(word, i, str2)) {
                    boolean fixed = false;

                    for (int j = m - 1; j >= 0 && !fixed; j--) {
                        int idx = i + j;
                        char original = word[idx];

                        for (char c = 'a'; c <= 'z'; c++) {
                            if (c == original) continue;

                            word[idx] = c;

                            // Must break F condition
                            if (matches(word, i, str2)) {
                                continue;
                            }

                            // Must NOT break any T condition
                            if (validAllT(word, str1, str2)) {
                                fixed = true;
                                break;
                            }
                        }

                        if (!fixed) {
                            word[idx] = original;
                        }
                    }

                    if (!fixed) return "";
                }
            }
        }

        return new String(word);
    }

    private boolean matches(char[] word, int start, String str2) {
        for (int j = 0; j < str2.length(); j++) {
            if (word[start + j] != str2.charAt(j)) {
                return false;
            }
        }
        return true;
    }

    private boolean validAllT(char[] word, String str1, String str2) {
        int n = str1.length();
        int m = str2.length();

        for (int i = 0; i < n; i++) {
            if (str1.charAt(i) == 'T') {
                for (int j = 0; j < m; j++) {
                    if (word[i + j] != str2.charAt(j)) {
                        return false;
                    }
                }
            }
        }
        return true;
    }
}